### ISSUE TITLE
Embedding ChakraCore - sample link aka.ms/jsrtwrapper points to 404

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore-wiki#14]
https://aka.ms/jsrtwrapper needs an update. It currently points to
https://github.com/Microsoft/Chakra-Samples/tree/master/ChakraCore%20Samples/Hello%20World/C%23/HelloWorld/Hosting
which is a dead link.

Should probably be:
https://github.com/Microsoft/Chakra-Samples/tree/master/ChakraCore%20Samples/Hello%20World/Windows/C%23/HelloWorld/Hosting

**Comment by dilijev** [comment]
@liminzhu ping

**Comment by liminzhu** [comment]
Fixed. Thanks for pointing out!
