### ISSUE TITLE
Add a page describing post-release support lifecycle.

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore-wiki#20]
It seems like there's some confusion over which versions of ChakraCore we will be shipping patch updates to. My understanding was that we're going to support the current and previous releases (N & N-1). Since our current release is `1.3.*` that would mean we will support `1.2.*` and `1.3.*` with patch releases. When `1.4.0` is released, we will stop supporting `1.2.*` (no more patch releases), but we will continue to support `1.3.*`.

Can we clarify whether this is indeed the approach we are planning to take and add content to the Wiki documenting this intention for the community?

/cc @digitalinfinity

**Comment by EdMaurer** [comment]
Your understanding is incorrect. The ChakraCore servicing policy is to service the current release only (and master of course).

**Comment by dilijev** [comment]
In that case, following release `1.4.0` we will only provide patch releases for `1.4`, e.g. `1.4.1`, and drop support for `1.2.*` and `1.3.*` which we have been supporting so far.

I'm not sure it's important to explicitly mention support of master since that's always going to be our work-in-progress branch.

I'm happy we are able to use this opportunity to get everyone on the same page, because both @digitalinfinity and @curtisman have described support via the N & N-1 approach I described above.
