### ISSUE TITLE
Clarify JsCallFunction pointer argument is an array of JsValueRefs

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore-wiki#31]
See https://github.com/Microsoft/ChakraCore/issues/2607#issuecomment-283748922

**Comment by liminzhu** [comment]
Made the change. 

https://github.com/Microsoft/ChakraCore/wiki/JsCallFunction/_compare/776013002b865aea72628d7ddb14d7a73b9ab870

**Comment by dilijev** [comment]
Thanks!
